### ISSUE TITLE
What is the value of shape?

### ISSUE THREAD

**Issue by TranPhuc9898** [CodeByRahulSaini/react-native-painting-app#1]
**### _Can I bother you, currently the shape is not json so how can I save what I drew in redux or bring everything I drew into another page and edit it? get it_**

**Comment by CodeByRahulSaini** [comment]
Check these files:
`src/index.tsx`
`src/hooks/useCanvas.tsx`
`src/components/Shape.tsx`

We have something like this in `index.tsx`:
```
<Canvas style={styles.canvas} onTouch={touchHandler}>
          {shapes.map((shape, index) => (
            <Shape key={index} {...shape} />
          ))}
          {currentShape && <Shape {...currentShape} />}
 </Canvas>
```

Sample `shapes` state:  
```
[
  {
     tool: 'circle',
      coordinates: { cx:10, cy:10, r:100},
      color: 'red',
      strokeWidth: 10
  }
]
```

We can store the same array in redux too.

**Comment by CodeByRahulSaini** [comment]
Let me know if you still have any questions!
